name: Publish Package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
      - name: Add token to .npmrc
        env:
          token: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=$token" >> .npmrc
      - name: Install npm
        run: npm install --package-lock-only
      - name: Build and test
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
